### ISSUE TITLE
Execute test migrations

### ISSUE THREAD

**Issue by lxatrhea** [RHEAGROUP/CDP4-Server-Administration-Tool#93]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-SDK
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-Server-Administration-Tool/issues) and [closed](https://github.com/RHEAGROUP/CDP4-Server-Administration-Tool/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Execute test migrations.
Discuss fixes afterwards.

**Comment by cozminvelciu** [comment]
### The following topics need to be discussed and handled as separate issues:
* SAT output window needs to be improved
   * is too small (just making it larger might not be the best solution, as the whole SAT window is already too big for a 1080p monitor)
   * does not auto-scroll with the messages, remaining on the first line
   * message quality could be improved
   * there are some typos that need to be fixed
* it would be very nice to have some feedback from the server during the seeding process, as this step can take a very long time during which no information is displayed in the output window
* at the end of the migration seeding process on the CDP4 server the Webservices threw an error displayed in the logs, but all the models seemed to have been working anyway afterwards; this needs further investigation
```
2021-01-29 14:34:20.5310|ERROR|CDP4WebServices.API.Modules.ExchangeFileImportyApi+<SeedDataStore>d__109.MoveNext|Unable to dump the datastore. 57014: canceling statement due to statement timeout    at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Npgsql.NpgsqlDataReader.<NextResult>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.<ExecuteReaderAsync>d__102.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlCommand.<ExecuteNonQuery>d__92.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at CDP4WebServices.API.Services.DataStore.DataStoreController.CloneDataStore() in C:\Users\Cozmin Velciu\Documents\Repositories\RHEA\CDP4-WebServices-Community-Edition\CDP4WebServices.API\Services\DataStore\DataStoreController.cs:line 49
   at CDP4WebServices.API.Modules.ExchangeFileImportyApi.<SeedDataStore>d__109.MoveNext() in C:\Users\Cozmin Velciu\Documents\Repositories\RHEA\CDP4-WebServices-Community-Edition\CDP4WebServices.API\Modules\10-25\ExchangeFileImportyApi.cs:line 312
```
* ⚠️ it seems like the SAT migration process only takes into account the last iteration, instead of migrating all iterations present; this needs to be changed ASAP

### Other:
* had an issue with not being able to use a "migration.json" file on development, had to switch back to an older version to get it to work, and when I switched back again it kept working
* the seeding process on the server takes a very long time (with no user feedback during the process): on my machine it was ~1h for 28 models
```
13:40:12 Export operation start
13:40:12 Pushing data to http://localhost:5000/Data/Exchange
14:34:20 Export operation end
```

**Comment by cozminvelciu** [comment]
Other than the above problems, the migration did work and all models were accessible on the new CDP4 target server.

**Comment by cozminvelciu** [comment]
The migration process was tested using a dump of the Redu (ESA Academy) server containing 28 models:
* from: a WSP v3.1.6 installation running locally on Docker in an Ubuntu VM
* to: a CDP4 Webservices installation running locally with:
   * the database (`rheagroup/cdp4-database-community-edition:latest`, 2.0.0) on Docker in a separate Ubuntu VM
   * the Webservices server on the Windows physical machine from a development branch ([#165](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues/165) necessary for a cyclic check critical bugfix)
* using: development version (v1.0.0) of SAT

**Comment by cozminvelciu** [comment]
Spawned issues:
* SAT: #96, #97
* WebServices: #183, #184
